server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/intellifinance
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
    show_sql: true
    properties:
      hibernate:
        format_sql: true