spring:
    datasource:
      url: jdbc:postgresql://database:5432/intellifinance
      username: postgres
      password: 1234

    jpa:
      hibernate:
        ddl-auto: validate
      show_sql: true
      properties:
        hibernate:
          format_sql: true

server:
  error:
    include-message: always

jwt:
  public:
    key: classpath:authz.pub
  private:
    key: classpath:authz.pem