CREATE TABLE cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_completo VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    data_nascimento DATE NOT NULL,
    senha VARCHAR(128) NOT NULL,
    perfil_indicado TEXT NOT NULL,
    renda_mensal NUMERIC(15, 2) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_cliente_renda
        CHECK (renda_mensal >= 0)
);

CREATE TABLE produto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    categoria VARCHAR(50) NOT NULL,
    versao INTEGER NOT NULL DEFAULT 1,
    descricao_tecnica TEXT NOT NULL,
    descricao_humanizada TEXT NOT NULL,
    perfil_indicado TEXT NOT NULL,
    renda_minima NUMERIC(15, 2) NOT NULL,
    taxa_juros_mensal NUMERIC(6, 4),
    valor_minimo NUMERIC(15, 2),
    valor_maximo NUMERIC(15, 2),
    prazo_minimo_meses INTEGER,
    prazo_maximo_meses INTEGER,
    criterios_elegibilidade JSONB,
    variaveis_simulacao JSONB,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_produto_categoria
        CHECK (categoria IN ('EMPRESTIMO_PESSOAL', 'CARTAO_CREDITO', 'FINANCIAMENTO', 'CONSORCIO', 'INVESTIMENTO')),
    CONSTRAINT ck_produto_renda_minima
        CHECK (renda_minima >= 0),
    CONSTRAINT ck_produto_valores
        CHECK (valor_minimo IS NULL OR valor_maximo IS NULL OR valor_minimo <= valor_maximo),
    CONSTRAINT ck_produto_prazos
        CHECK (prazo_minimo_meses IS NULL OR prazo_maximo_meses IS NULL OR prazo_minimo_meses <= prazo_maximo_meses)
);

CREATE TABLE sessao_atendimento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL,
    intencao_identificada VARCHAR(100),
    status VARCHAR(20) NOT NULL DEFAULT 'EM_ANDAMENTO',
    motivo_recusa TEXT,
    iniciado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    encerrado_em TIMESTAMPTZ,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_sessao_cliente
        FOREIGN KEY (cliente_id) REFERENCES cliente(id) ON DELETE CASCADE,
    CONSTRAINT ck_sessao_status
        CHECK (status IN ('EM_ANDAMENTO', 'SUCESSO', 'RECUSADO', 'ABANDONADO')),
    CONSTRAINT ck_sessao_encerramento
        CHECK (
            (status = 'EM_ANDAMENTO' AND encerrado_em IS NULL) OR
            (status <> 'EM_ANDAMENTO' AND encerrado_em IS NOT NULL)
        )
);

CREATE TABLE mensagem (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sessao_id BIGINT NOT NULL,
    origem VARCHAR(10) NOT NULL,
    conteudo TEXT NOT NULL,
    tool_utilizada VARCHAR(100),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_mensagem_sessao
        FOREIGN KEY (sessao_id) REFERENCES sessao_atendimento(id) ON DELETE CASCADE,
    CONSTRAINT ck_mensagem_origem
        CHECK (origem IN ('USER', 'IA', 'SYSTEM'))
);

CREATE TABLE simulacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sessao_id BIGINT NOT NULL,
    produto_id BIGINT NOT NULL,
    produto_versao INTEGER NOT NULL,
    valor_solicitado NUMERIC(15, 2) NOT NULL,
    prazo_meses INTEGER NOT NULL,
    taxa_juros_aplicada NUMERIC(6, 4) NOT NULL,
    valor_parcela NUMERIC(15, 2) NOT NULL,
    custo_total NUMERIC(15, 2) NOT NULL,
    selecionada BOOLEAN NOT NULL DEFAULT FALSE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_simulacao_sessao
        FOREIGN KEY (sessao_id) REFERENCES sessao_atendimento(id) ON DELETE CASCADE,
    CONSTRAINT fk_simulacao_produto
        FOREIGN KEY (produto_id) REFERENCES produto(id) ON DELETE RESTRICT,
    CONSTRAINT ck_simulacao_valores
        CHECK (valor_solicitado > 0 AND prazo_meses > 0 AND valor_parcela > 0 AND custo_total > 0)
);

CREATE TABLE contratacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sessao_id BIGINT NOT NULL UNIQUE,
    simulacao_id BIGINT NOT NULL UNIQUE,
    cliente_id BIGINT NOT NULL,
    produto_id BIGINT NOT NULL,
    produto_versao INTEGER NOT NULL,
    valor_contratado NUMERIC(15, 2) NOT NULL,
    prazo_meses INTEGER NOT NULL,
    taxa_juros_mensal NUMERIC(6, 4) NOT NULL,
    valor_parcela NUMERIC(15, 2) NOT NULL,
    custo_total NUMERIC(15, 2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
    criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_contratacao_sessao
        FOREIGN KEY (sessao_id) REFERENCES sessao_atendimento(id) ON DELETE CASCADE,
    CONSTRAINT fk_contratacao_simulacao
        FOREIGN KEY (simulacao_id) REFERENCES simulacao(id) ON DELETE RESTRICT,
    CONSTRAINT fk_contratacao_cliente
        FOREIGN KEY (cliente_id) REFERENCES cliente(id) ON DELETE CASCADE,
    CONSTRAINT fk_contratacao_produto
        FOREIGN KEY (produto_id) REFERENCES produto(id) ON DELETE RESTRICT,
    CONSTRAINT ck_contratacao_status
        CHECK (status IN ('PENDENTE', 'APROVADO', 'RECUSADO', 'CANCELADO'))
);

-- Índices
CREATE INDEX idx_cliente_email ON cliente(email);
CREATE INDEX idx_cliente_ativo ON cliente(ativo);
CREATE INDEX idx_produto_ativo ON produto(ativo);
CREATE INDEX idx_produto_versao ON produto(versao);
CREATE INDEX idx_produto_busca ON produto(categoria, ativo, renda_minima);
CREATE INDEX idx_sessao_cliente_id ON sessao_atendimento(cliente_id);
CREATE INDEX idx_sessao_status ON sessao_atendimento(status);
CREATE INDEX idx_sessao_iniciado_em ON sessao_atendimento(iniciado_em);
CREATE INDEX idx_mensagem_sessao_id ON mensagem(sessao_id);
CREATE INDEX idx_mensagem_origem ON mensagem(origem);
CREATE INDEX idx_simulacao_sessao_id ON simulacao(sessao_id);
CREATE INDEX idx_simulacao_produto_id ON simulacao(produto_id);
CREATE UNIQUE INDEX uk_simulacao_selecionada_por_sessao ON simulacao(sessao_id) WHERE selecionada = TRUE;
CREATE INDEX idx_contratacao_cliente_id ON contratacao(cliente_id);
CREATE INDEX idx_contratacao_produto_id ON contratacao(produto_id);
CREATE INDEX idx_contratacao_status ON contratacao(status);